.gitignore, server/.vscode/launch.json, server/config/config.js, server/index.js, server/models/enterprise-model.js, server/models/tag-model.js, server/models/user-model.js, server/models/video-model.js, server/package.json, server/routes/enterprise.js, server/routes/user.js
=> Feat: Backend - Basic Routing Prototype

Client/client/app/Login/Login.component.scss, Client/client/app/Login/Login.html, Client/client/index.ejs, Client/package-lock.json, Client/package.json, server/package-lock.json
Created the view for user and enterprise login pages
=> feat(FrontEnd: login) - Login Pages for user and enterprise

.gitignore, Client/client/app/app.controller.js, Client/client/app/app.module.js, Client/client/app/user/user.html, Client/client/app/videoPlayer/video.component.js, Client/client/app/videoPlayer/video.component.scss, Client/client/app/videoPlayer/video.controller.js, Client/client/app/videoPlayer/videoPlayer.html, package-lock.json
Added a video player component supported by Angular
=> feat(videoPlayer): added video player component

Client/package-lock.json, Client/package.json
added modules in package.json and fixed build.
=> fix(build): added modules in package.json

Client/client/app/Login/Login.html, Client/client/app/app.module.js, Client/client/app/enterprise/enterprise.controller.js, Client/client/app/enterprise/enterprise.html, Client/package-lock.json, Client/package.json
added video upload option. Currently supporting .mp4 format.
=> feat(videoUpload): added video upload option

server/index.js, server/package.json, server/routes/enterprise.js
Feature Updates the database with user and enterprise details after signup
=> Feat : Backend - Create User/Enterprise details in DB after Signup

server/index.js, server/routes/enterprise.js
This feature contains the code to upload the videos to database
=> Feat : Backend - Video Upload

server/package-lock.json, server/routes/enterprise.js, server/routes/user.js
addition of profile updation logic
=> Profile update

Client/client/app/Login/Login.controller.js, Client/client/app/Login/Login.html, Client/client/app/app.module.js, Client/client/app/user/user.controller.js, Client/client/index.ejs, Client/package-lock.json, Client/package.json
added state avigation and its views
=> feat(states): added state navigation

server/index.js, server/models/enterprise-model.js, server/models/user-model.js, server/routes/enterprise.js
This feature handles the enterprise details request from the frontend and
sends the required data in response
=> Feat : Backend - Handle the details Request

server/routes/enterprise.js
This feature cotains the code to fetch video from the database by filename
=> Feat : Backend - Fetch Video By Filename

server/routes/user.js
This feature contains the code to perform like on a video
=> Feat : Backend - Like Video

Client/client/app/Login/Login.controller.js, Client/client/app/Login/login.service.js, Client/client/app/enterprise/enterprise.controller.js, Client/client/app/enterprise/enterprise.html, Client/client/app/enterprise/enterprise.service.js
=> feat(enterprise-ui): added view for enterprise

server/routes/user.js
This feature contains the code to handle the views once a video is watched
completely.
=> Feat : Backend - Handle Number of Views for a video

server/package-lock.json, server/package.json, server/routes/user.js
added feature logic to display 10 videos to display to user at login
=> Feat : Backend - top 10 videos to display to user

Client/client/app/Login/Login.controller.js, Client/client/app/Login/Login.html
Fixed selected user type from defualt enterprise type
=> fix(userType): fixed selected user type

Client/client/app/Login/login.service.js, Client/client/app/videoPlayer/video.controller.js
fixed a route url to fetch details after login
=> fix(loginDetails): fixed details api request

server/routes/user.js
This feature contains the code to return the list of videos once the user logs in
=> Feat : Backend - Return list of videos

Client/client/app/Login/Login.html, Client/client/app/Login/login.service.js, Client/client/app/app.component.html, Client/client/app/app.module.js, Client/client/app/enterprise/enterprise.controller.js, Client/client/app/enterprise/enterprise.html
Added enterprise login feature
=> feat(enterprise-login): added enterprise login

server/routes/enterprise.js, server/routes/user.js
updated logic for enterprise and user profile updations
=> fix : backend - user and enterprise profile updation fields

server/routes/user.js
Contains fix related to password change for user
=> Fix : Backend - Change password

server/routes/enterprise.js, server/routes/user.js
Contains enterprise password update feature
=> Feat : Backend - update enterprise password

server/routes/enterprise.js, server/routes/user.js
This feature contains the code to send the metadata of mongodb object once the file is uploaded
=> Feat : Backend - return metadata video object

server/routes/enterprise.js, server/routes/user.js
Contains the fix to fetch video from user instead of fetching from
enterprise
=> Fix : Backend - Fetch Video From user

Client/client/app/Login/Login.controller.js, Client/client/app/Login/Login.html, Client/client/app/app.module.js, Client/client/app/user/user.controller.js, Client/client/app/user/user.html, Client/client/app/user/user.service.js, Client/client/app/videoPlayer/video.component.js, Client/client/app/videoPlayer/video.controller.js, Client/client/app/videoPlayer/video.service.js, Client/client/app/videoPlayer/videoPlayer.html, Client/package.json
=> feat(user-login): added user-login

server/routes/enterprise.js
Contains code to add tags along with videos. Useful for tag-based search
=> Feat : Backend - Add tags along with videos

Client/client/app/user/user.controller.js, Client/client/app/user/user.html, Client/client/app/user/user.service.js, Client/client/index.ejs, Client/client/index.html
=> feat(user-comments): added user comments

Client/client/app/Login/login.service.js, Client/client/app/enterprise/enterprise.controller.js, Client/client/app/enterprise/enterprise.service.js, Client/client/app/user/user.service.js, Client/client/app/videoPlayer/video.service.js
=> fix(url): fixed backend urls

Client/client/app/app.component.html, Client/client/app/app.module.js
Fixed the changes due to the previous merge request.
=> fix(merge): fixed code due to previous mr

Client/client/app/Login/Login.controller.js, Client/client/app/Login/Login.html, Client/client/app/enterprise/enterprise.controller.js, server/routes/user.js
fixed login of users and enterprises
=> fix(login): fixed login of users/enterprises

Client/client/app/Login/Login.controller.js, Client/client/app/enterprise/enterprise.controller.js, Client/client/app/enterprise/enterprise.html, Client/client/app/enterprise/enterprise.service.js
Updated coins and video upload functionalities
=> feat(e-coins): updated coins and video upload fn

server/routes/enterprise.js
=> fix : Backend - refactor delete video code

Client/client/app/Login/login.service.js, Client/client/app/app.component.html, Client/client/app/enterprise/enterprise.controller.js, Client/client/app/user/user.controller.js, Client/client/app/user/user.html, Client/client/app/user/user.service.js, Client/client/app/videoPlayer/video.component.js, Client/client/app/videoPlayer/video.component.scss, Client/client/app/videoPlayer/video.controller.js, Client/client/app/videoPlayer/videoPlayer.html
Added a video list for the user to select the videos from and also added
the comments section for the video
=> feat(user): added video list and comments

Client/client/app/Login/Login.controller.js, Client/client/app/Login/Login.html, Client/client/app/Login/login.service.js, Client/client/app/enterprise/enterprise.controller.js, Client/client/app/enterprise/enterprise.html, Client/client/app/enterprise/enterprise.service.js, Client/client/app/videoPlayer/video.controller.js
refactored enterprise login and fixed few bugs
=> refactor(enterprise): refactored enterprise login

Client/client/app/Login/Login.controller.js, Client/client/app/Login/Login.html, Client/client/app/videoPlayer/video.controller.js, Client/client/app/videoPlayer/videoPlayer.html
=> refactor(user): refactored user code

Client/client/app/videoPlayer/video.controller.js
fixed the body sent in request when the user watches the video
=> fix(user-video): fixed a request to backend

server/index.js
session creation while user logs in
=> feat: user session creation when logged in

Client/client/app/app.module.js, Client/client/app/enterprise/enterprise.controller.js, Client/client/app/enterprise/enterprise.html, Client/client/app/search/search.component.js, Client/client/app/search/search.controller.js, Client/client/app/search/search.html, Client/client/app/user/user.controller.js, Client/client/app/user/user.html
=> feat(search): added search functionality

Client/client/app/Login/Login.controller.js, Client/client/app/app.controller.js
fixed the login checks that have to be done
=> fix(login-check): fixed login check

Client/client/app/enterprise/enterprise.controller.js, Client/client/app/enterprise/enterprise.html
=> fix(enterprise): fixed enterprise page

Client/client/app/enterprise/enterprise.controller.js, Client/client/app/enterprise/enterprise.html
made style changes to enterpris html
=> style(enterprise): made style changes

Client/client/app/search/search.controller.js, Client/client/app/search/search.html, Client/client/app/services/sessionService.js, Client/client/app/user/user.controller.js, Client/client/app/user/user.html, Client/client/app/videoPlayer/videoPlayer.html
fixed enterprise functionality
=> fix(enterprise): fixed enterprise functionality

Client/client/app/enterprise/enterprise.controller.js, Client/client/app/enterprise/enterprise.html, Client/client/app/search/search.html
=> fix(enterrpise): fixed etnerprise page

Client/client/app/Login/login.service.js, Client/client/app/user/user.controller.js, Client/client/app/user/user.html, Client/client/app/videoPlayer/video.controller.js, Client/client/app/videoPlayer/videoPlayer.html
=> style(enterprise): styled enterprise page

Client/client/app/search/search.component.js, Client/client/app/search/search.controller.js, Client/client/app/search/search.html
=> fix(search): fixed search functionality

server/index.js, server/package.json, server/routes/enterprise.js, server/routes/user.js
pass json array to front end stats displayed by D3JS in front end
=> feat: backend - compatible code to D3js

Client/client/app/Login/Login.html, Client/client/app/enterprise/enterprise.controller.js, Client/client/app/enterprise/enterprise.service.js, Client/client/app/user/user.controller.js, Client/client/app/user/user.service.js, Client/client/app/videoPlayer/video.controller.js
=> refasctor(app): refactored app

Client/client/app/Login/Login.controller.js, Client/client/app/user/user.controller.js, Client/client/app/user/user.html, Client/client/app/user/user.service.js
=> fix(issues): fixed multiple issues

Client/client/app/Login/Login.component.scss, Client/client/app/Login/Login.controller.js, Client/client/app/enterprise/enterprise.html, Client/client/app/user/user.component.scss, Client/client/app/user/user.controller.js, Client/client/app/user/user.html, Client/client/app/videoPlayer/video.component.js, Client/client/app/videoPlayer/video.controller.js
=> fiz(multiple): fixed multipple issues

Client/client/app/enterprise/enterprise.controller.js, Client/client/app/enterprise/enterprise.html, Client/client/app/enterprise/enterprise.service.js
=> fix(previousMerge): fixed issue from previous MR
